### ISSUE TITLE
Timestamp on solution submitted

### ISSUE THREAD

**Issue by michele6000** [michele6000/AI_Project#14]
From docs: " le varie immagini corrispondenti alle differenti fasi dell’elaborato, così come i timestamp in cui vengono caricate, non devono essere scartati o sovra scritti di volta in volta, ma occorre mantenerne memoria per poter rivedere anche successivamente l’evoluzione della prova"

- [x] Add timestamp of solution to DB (Server)
- [x] Add timestamp on Solution entity (Server)
- [x] Set automatically timestamp on addSolution call from studentController (Server)
- [x] Show timestamp of solution ( Solution History, Last Solution, both student and professor view, in particular in professor view add a column in main table solution listed by submission id, if present show timestamp of latest else empty column, in history shaw always all ) (Client)

From docs: " Qui gli elaborati devono poter essere filtrati in base al loro stato (es. visualizzare tutti quelli NULL, cioè non ancora letti dallo studente, oppure tutti quelli consegnati e da rivedere) e ordinati in ordine temporale. Per ogni elaborato occorre poter vedere il nome, cognome, matricola dello studente a cui corrisponde, lo stato e il timestamp in cui quello stato è stato assegnato."

- [x] Add filter by solution status, sort by timestamp

From docs: "rivedere l’elaborato “caricato” in ciascuna delle fasi passate, e *caricare la sua correzione* indicando se attenderà o no da parte dello studente una revisione o se questo è da considerarsi l’elaborato definitivo. In quest’ultimo caso il docente assegnerà anche un voto o un giudizio all’elaborato. "

- [x] Add @lob to solution, correction is O2O with solution,  correction management ( simple pdf upload, upload correction + evaluation = EVALUATED, only correction = REQUEST_REVIEW)
- [x] Replace REVIEWED with REQUEST_REVIEW ( solution status )
- [x] Add endpoint addCorrection intead of call getSolution
- [x] Add in professor view -> review modal : button to upload file (correction) + optional message (send via mail)
- [x] Add in professor view -> evaluate modal : optional button to upload file (correction) + mark 
- [x] Endpoint (POST): addCorrection 
    - Type : Evaluation -> RequestPart(file) ==/!= null + RequestPart(Long : mark) 1<mark<31
    - Type : Review -> RequestPart(file) != null + RequestPart(Stringa : messaggio) ==/!= null 
    - DddCorrection( @RequestPart('file') ,@RequestPart('mark'), @RequestPart('message')

**Comment by michele6000** [comment]
Better to add a @Lob to solution, correction is O2O with solution.

**Comment by michele6000** [comment]
- [ ] Add endpoint addCorrection intead of call getSolution
- [ ] Add dialog in professor view when click review to add a correction,
- [ ] Add in the evaluate dialog also a add correction button

-> Correction is always a pdf file.

**Comment by Iustin-Burlacu** [comment]
@michele6000 in evaluation: server side file must not be required
